# Generated by Django 4.0.4 on 2022-05-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('direction', models.CharField(max_length=255)),
                ('cellphone', models.IntegerField()),
                ('total', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='date create')),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.city')),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.department')),
                ('id_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.documenttype')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.product')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='id_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.department'),
        ),
    ]
